# Generated by Django 3.1.4 on 2022-05-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Office_Name', models.CharField(max_length=100)),
                ('Office_Address', models.TextField()),
                ('District', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Active_Status_ID', models.IntegerField(null=True)),
                ('Remarks', models.CharField(max_length=200)),
            ],
        ),
    ]
