# Generated by Django 3.1.4 on 2022-05-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active_Statuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Active_Status_Name', models.CharField(max_length=20)),
                ('Remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expenditure_Type_Name', models.CharField(max_length=100)),
                ('Active_Status_ID', models.IntegerField(null=True)),
                ('Updated_Date', models.DateField()),
                ('Update_User_ID', models.IntegerField(null=True)),
                ('Remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Income_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Income_Type_Name', models.CharField(max_length=100)),
                ('Active_Status_ID', models.IntegerField(null=True)),
                ('Updated_Date', models.DateField()),
                ('Update_User_ID', models.IntegerField(null=True)),
                ('Remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
