# Generated by Django 3.1.4 on 2022-05-06 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20220506_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Income_Name', models.CharField(max_length=100)),
                ('Update_User_ID', models.IntegerField()),
                ('Update_Date', models.DateField()),
                ('Remarks', models.CharField(max_length=100)),
                ('Active_Status_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.active_statuses')),
                ('Income_Type_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.income_types')),
            ],
        ),
        migrations.CreateModel(
            name='Expences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expence_Name', models.CharField(max_length=100)),
                ('Update_User_ID', models.IntegerField()),
                ('Update_Date', models.DateField()),
                ('Remarks', models.CharField(max_length=100)),
                ('Active_Status_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.active_statuses')),
                ('Expenditure_Type_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.expenditure_types')),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Incomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_Date', models.DateField()),
                ('Receipt_ID', models.IntegerField()),
                ('Received_Amount', models.IntegerField()),
                ('Transaction_Made_BY', models.CharField(max_length=100)),
                ('Updated_User_ID', models.IntegerField()),
                ('Update_Date', models.DateField()),
                ('Remarks', models.CharField(max_length=100)),
                ('Income_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.incomes')),
                ('Office_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.offices')),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Expences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expence_Date', models.DateField()),
                ('Expend_Amount', models.IntegerField()),
                ('Transaction_Made_BY', models.CharField(max_length=100)),
                ('Updated_User_ID', models.IntegerField()),
                ('Update_Date', models.DateField()),
                ('Remarks', models.CharField(max_length=100)),
                ('Expence_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.expences')),
                ('Office_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.offices')),
            ],
        ),
    ]
