# Generated by Django 3.1.4 on 2022-06-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_daily_expences_daily_incomes_expences_incomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_incomes',
            name='Remarks',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='daily_incomes',
            name='Transaction_Made_BY',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='daily_incomes',
            name='Update_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='daily_incomes',
            name='Updated_User_ID',
            field=models.IntegerField(null=True),
        ),
    ]
