# Generated by Django 3.1.4 on 2022-07-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20220622_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_expences',
            name='Remarks',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='daily_expences',
            name='Transaction_Made_BY',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='daily_expences',
            name='Update_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='daily_expences',
            name='Updated_User_ID',
            field=models.IntegerField(null=True),
        ),
    ]
