# Generated by Django 3.1.4 on 2022-08-03 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20220727_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receiver_Name', models.CharField(max_length=100)),
                ('Designation', models.TextField(max_length=90, null=True)),
                ('Remarks', models.CharField(max_length=100, null=True)),
                ('Active_Status_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.active_statuses')),
                ('Office_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.offices')),
            ],
        ),
    ]
