# Generated by Django 3.1.4 on 2022-08-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_receivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivers',
            name='Designation',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='receivers',
            name='Remarks',
            field=models.CharField(max_length=100),
        ),
    ]
