# Generated by Django 3.1.4 on 2022-08-03 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20220804_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_expences',
            name='Receiver_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.receivers'),
        ),
    ]
